# Fonts
tap "homebrew/cask-fonts"
cask "font-fira-code"

# shell tools
cask "ghostty"
brew "zsh"
brew "yarn"
brew "fzf"
brew "duti"

# vim tools
brew "vim"

# editors
cask "visual-studio-code"

# apps
cask "arc"
cask "spotify"

# languages
brew "nvm"
brew "pyenv"
